name: Reusable Workflow
on:
  workflow_call:
      inputs:
        message:
          required: true
          type: string


jobs:
  display_message:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Display Message
        run: echo "${{ inputs.message }}"
